name: NodeJS with Vite

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        pnpm:
          - 7.14.0

    steps:
      - uses: actions/checkout@v3

      - name: Build
        run: |
          pnpm install
          pnpm run build
